default_restore_strategy: copy
accounts:
  - id: "123456789012"
    name: "Cuenta 1"
    role_arn: "arn:aws:iam::123456789012:role/BackupOperator"
    region: "us-east-1"
    backup_bucket: "cuenta1-backups"
    backup_prefix: "snapshots/"
    restore_bucket: "cuenta1-restore"
    restore_prefix: "manual/"
  - id: "210987654321"
    name: "Cuenta 2"
    role_arn: "arn:aws:iam::210987654321:role/BackupOperator"
    region: "us-west-2"
    backup_bucket: "cuenta2-backups"
    backup_prefix: "snapshots/"
    restore_bucket: "cuenta2-restore"
    restore_prefix: "manual/"
